name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: docker build -t mynestjs15 --build-arg SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }} --build-arg SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }} .

    - name: Tag Docker image
      run: docker tag mynestjs15:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push Docker image to ECR
      run: docker push ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Update task definition with new image
      id: task-def
      run: |
        TASK_FAMILY=$(aws ecs describe-services --cluster ${{ secrets.CLUSTER_NAME }} --services ${{ secrets.SERVICE_NAME }} --query 'services[0].taskDefinition' --output text | awk -F'/' '{print $2}' | awk -F':' '{print $1}')
        TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY)
        NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE_URI "${{ secrets.ECR_REPOSITORY }}:latest" '.taskDefinition.containerDefinitions[0].image=$IMAGE_URI')
        echo "$NEW_TASK_DEF" > new-task-def.json
        aws ecs register-task-definition \
          --cli-input-json file://new-task-def.json

    - name: Update ECS service with new task definition
      run: |
        NEW_TASK_DEF_ARN=$(cat new-task-def.json | jq -r '.taskDefinition.taskDefinitionArn')
        aws ecs update-service --cluster ${{ secrets.CLUSTER_NAME }} --service ${{ secrets.SERVICE_NAME }} --task-definition $NEW_TASK_DEF_ARN --force-new-deployment
